#name: bpp_frontend
#description: "A new Flutter project."
#version: 1.0.0+1
#
#environment:
#  sdk: ">=3.5.4 <4.0.0"
#
#dependencies:
#  flutter:
#    sdk: flutter
#  cupertino_icons: ^1.0.8
#  get: ^4.6.5
#  flutter_map: ^6.2.1
#  latlong2: ^0.9.1
#  animated_text_kit: ^4.2.2
#  font_awesome_flutter: ^10.4.0
#  liquid_progress_indicator: ^0.4.0
#  formz: ^0.4.1
#  equatable: ^2.0.5
#  bloc: ^8.0.0
#  flutter_bloc: ^8.1.3
#  responsive_framework: ^1.5.1
#  lucide_icons: ^0.257.0
#  flutter_svg: ^2.0.7
#  go_router: ^14.6.1
#  fl_chart: ^0.69.2
#  intl: ^0.20.1
#  confetti: ^0.7.0
#
#  dotted_line: ^3.2.3  #newly added
#  image_picker: ^1.1.2  #newly added
#  http: ^1.2.2
#  file_picker: ^8.1.4
#  shared_preferences: ^2.0.11
#
#
#
#
#
#
#dev_dependencies:
#  flutter_test:
#    sdk: flutter
#  flutter_lints: ^5.0.0
#  flutter_launcher_icons: ^0.14.2 # Downgraded to the correct version
#  flutter_icons:
#    image_path: "icons/first.png"
#    android: true
#    ios: true
#
#
#
#
#
#flutter:
#  uses-material-design: true
#  assets:
#    - assets/fonts/
#    - assets/images/
#    - assets/icons/
#    - assets/fonts/
#
#  fonts:
#    - family: Anton
#      fonts:
#        - asset: assets/fonts/Anton/Anton-Regular.ttf
#
#    - family: Mukta
#      fonts:
#        - asset: assets/fonts/Mukta-Regular.ttf
#        - asset: assets/fonts/Mukta-Medium.ttf
#        - asset: assets/fonts/Mukta-Bold.ttf
#
#    - family: BebasNeue
#      fonts:
#        - asset: assets/fonts/BebasNeue-Regular.ttf
#
#    - family: Archivo
#      fonts:
#        - asset: assets/fonts/Archivo/ArchivoBlack-Regular.ttf
#
#    - family: Oswald
#      fonts:
#        - asset: assets/fonts/Oswald/Oswald-Regular.ttf
#        - asset: assets/fonts/Oswald/Oswald-Medium.ttf
#        - asset: assets/fonts/Oswald/Oswald-Bold.ttf
#        - asset: assets/fonts/Oswald/Oswald-SemiBold.ttf


name: bpp_frontend
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  sms_autofill: ^2.4.1

  dio: ^5.0.0
  get: ^4.6.5
  flutter_map: ^6.2.1
  latlong2: ^0.9.1
  animated_text_kit: ^4.2.2
  font_awesome_flutter: ^10.4.0
  liquid_progress_indicator: ^0.4.0
  formz: ^0.4.1
  equatable: ^2.0.5
  bloc: ^8.0.0
  flutter_bloc: ^8.1.3
  responsive_framework: ^1.5.1
  lucide_icons: ^0.257.0
  flutter_svg: ^2.0.7
  go_router: ^14.6.1
  fl_chart: ^0.69.2
  intl: ^0.20.1
  confetti: ^0.7.0
  dotted_line: ^3.2.3
  image_picker: ^1.1.2
  http: ^1.2.2
  file_picker: ^8.1.4
  url_launcher: ^6.3.1

  shared_preferences: ^2.0.11

  #path_provider: ^2.1.1
  path_provider: ^2.1.2
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2
#
#flutter_icons:
#  image_path: "icons/apple_logo4.png"
#  android: true
#  ios: true

flutter_icons:
  image_path: "icons/bpp23.jpg"
  android: true
  ios: true


flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton/Anton-Regular.ttf

    - family: Mukta
      fonts:
        - asset: assets/fonts/Mukta-Regular.ttf
        - asset: assets/fonts/Mukta-Medium.ttf
        - asset: assets/fonts/Mukta-Bold.ttf

    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf


    - family: Impact
      fonts:
        - asset: assets/fonts/Impact/impact.ttf
        - asset: assets/fonts/Impact/impacted.ttf
        - asset: assets/fonts/Impact/unicode.impact.ttf
       # - asset: fonts/Impact-Bold.ttf
          weight: 700


    - family: Archivo
      fonts:
        - asset: assets/fonts/Archivo/ArchivoBlack-Regular.ttf

    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald/Oswald-Regular.ttf
        - asset: assets/fonts/Oswald/Oswald-Medium.ttf
        - asset: assets/fonts/Oswald/Oswald-Bold.ttf
        - asset: assets/fonts/Oswald/Oswald-SemiBold.ttf
