name: bpp_frontend
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.5
  flutter_map: ^6.2.1
  latlong2: ^0.9.1
  animated_text_kit: ^4.2.2
  font_awesome_flutter: ^10.4.0
  liquid_progress_indicator: ^0.4.0
  formz: ^0.4.1
  equatable: ^2.0.5
  bloc: ^8.0.0
  flutter_bloc: ^8.1.3
  responsive_framework: ^1.5.1
  lucide_icons: ^0.257.0
  flutter_svg: ^2.0.7
  go_router: ^14.6.1
  fl_chart: ^0.69.2
  intl: ^0.20.1
  confetti: ^0.7.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Downgraded to the correct version

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton/Anton-Regular.ttf

    - family: Mukta
      fonts:
        - asset: assets/fonts/Mukta-Regular.ttf
        - asset: assets/fonts/Mukta-Medium.ttf
        - asset: assets/fonts/Mukta-Bold.ttf

    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf

    - family: Archivo
      fonts:
        - asset: assets/fonts/Archivo/ArchivoBlack-Regular.ttf

    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald/Oswald-Regular.ttf
        - asset: assets/fonts/Oswald/Oswald-Medium.ttf
        - asset: assets/fonts/Oswald/Oswald-Bold.ttf
        - asset: assets/fonts/Oswald/Oswald-SemiBold.ttf
