name: bpp_frontend
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.5  # Add this line to include the GetX package
  font_awesome_flutter: ^10.4.0  # Ensure this dependency is here
  flutter_map: ^4.0.0   # Upgraded to the latest version of flutter_map (4.0.0)
  latlong2: ^0.8.1       # Use the latest version of latlong2
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/Mukta-Regular.ttf
        - asset: assets/fonts/Mukta-Medium.ttf
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        - asset: assets/fonts/BebasNeue/BebasNeue-Regular.ttf
